[build]
  base = "/"
  functions = "netlify/functions/teachers" # يشير إلى المجلد الفرعي لوظائف المعلمين

[functions.generateCertificateTwo2] # هذا التكوين لوظيفة شهادة الطالب الثانية
  included_files = ["fonts/arial.ttf"]

[functions.generateCertificateTwoTeacher4] # تكوين وظيفة شهادة المعلم الثانية
  included_files = ["fonts/arial.ttf"] # إذا كانت تستخدم نفس الخط أو خط آخر

[[redirects]]
  from = "/certificate/:id" # إعادة توجيه لشهادات الطلاب
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true

[[redirects]]
  from = "/teachers/certificate/:id" # إعادة توجيه لشهادات المعلمين
  to = "/.netlify/functions/generateCertificateTwoTeacher4/:id"
  status = 200
  force = true