[functions]
  # تحديد المسار الذي توجد فيه دوال Netlify
  directory = "netlify/functions"
  
  # تحديد وحدة node-fetch كوحدة خارجية ليتم حزمها بواسطة Netlify
  # هذا يضمن أن يتم تضمين node-fetch في حزمة الدالة عند النشر.
  external_node_modules = ["node-fetch"]
  
  # تضمين جميع الملفات داخل مجلد node_modules/node-fetch لضمان عمل المكتبة بشكل صحيح.
  included_files = ["node_modules/node-fetch/**"]

  # يمكن إضافة إعدادات أخرى هنا إذا لزم الأمر، مثل وقت انتهاء مهلة الدالة (timeout).
  # timeout = 10 # بالثواني