# netlify.toml

[build]
  base = "/"
  # قم بتعيين مجلد النشر إلى مجلد الوظائف نفسه
  # لأن وظيفتك هي التي تولد المحتوى بالكامل.
  publish = "netlify/functions" 
  functions = "netlify/functions"

[functions]
  included_files = [
    # تم إزالة "public/**" لأن مجلد public لم يعد موجوداً أو لا يحتوي على ملفات للنشر.
    "netlify/functions/arial.ttf",
    "netlify/functions/data/certificateData.js", # مسار ملف Base64 الجديد
    "node_modules/mongodb/**",
    "node_modules/bson/**"
  ]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true