# netlify.toml

[build]
  base = "/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = [
    "public/**", # لتضمين مجلد public بالكامل (لصورة wwee.jpg)
    "netlify/functions/arial.ttf", # لتضمين ملف الخط arial.ttf
    "node_modules/mongodb/**",
    "node_modules/bson/**"
  ]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true