[build]
  base = "/"
  functions = "netlify/functions"

[functions]
  included_files = ["public/**", "netlify/functions/jimp_fonts/**", "node_modules/sharp/**", "node_modules/sharp-linux-x64/**"]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true