# netlify.toml

[build]
  base = "/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = [
    "public/**",
    "netlify/functions/arial.ttf",
    "netlify/functions/data/certificateData.js", # **أضف هذا السطر لتضمين ملف Base64**
    "node_modules/mongodb/**",
    "node_modules/bson/**"
  ]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true