[build]
  base = "/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = [
    "node_modules/mongodb/**",
    "node_modules/bson/**",
    "node_modules/node-fetch/**" # هذا السطر مهم للتأكد من تضمين الحزمة
  ]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true