<a href="/.netlify/functions/generateCertificateTwo2/معرف_الطالب_هنا" target="_blank" class="print-btn">
    عرض الشهادة (نافذة جديدة)
</a>

<button onclick="openCertificate()">عرض الشهادة</button>

<script>
function openCertificate() {
    const studentId = 'معرف_الطالب_الحالي'; // يجب أن تحصل على معرف الطالب من مكان ما في صفحتك
    window.open(`/.netlify/functions/generateCertificateTwo2/${studentId}`, '_blank');
}
</script>