[build]
  base = "/"
  functions = "netlify/functions"

[functions]
  included_files = ["public/images_temp/**", "fonts/arial.ttf"]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true