[build]
  functions = "netlify/functions"
  publish = "public"

[[redirects]]
  from = "/generateCertificateTwo2"
  to = "/.netlify/functions/generateCertificateTwo2"
  status = 200

# تضمين ملف الخط مع دالة generateCertificateTwo2
[functions.generateCertificateTwo2]
  included_files = ["fonts/arial.ttf", "certificate_template.html"]