# netlify.toml

[build]
  base = "/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = [
    # ******** انتبه هنا: تأكد من المسار الفعلي لصورتك ********
    # يجب أن يكون هذا المسار هو نفسه الذي وضعته في generateCertificateTwo2.js
    "public/images/full/wwee.jpg", 
    "public/fonts/arial.ttf",
    "node_modules/mongodb/**",
    "node_modules/bson/**",
    "node_modules/chrome-aws-lambda/**", # تضمين chrome-aws-lambda
    "node_modules/puppeteer-core/**",
    "node_modules/qrcode/**" # تضمين qrcode
  ]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true