# netlify.toml

[build]
  base = "/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = [
    "public/images/full/wwee.jpg", # لتضمين ملف الصورة لقالب الشهادة
    "public/fonts/arial.ttf",     # لتضمين ملف الخط العربي
    "node_modules/mongodb/**",    # لتضمين مكتبة MongoDB
    "node_modules/bson/**",        # لتضمين مكتبة BSON (تبعية لـ MongoDB)
    "node_modules/chrome-aws-lambda/**", # لتضمين مكتبة chrome-aws-lambda وجميع تبعياتها
    "node_modules/puppeteer-core/**" # لتضمين مكتبة puppeteer-core
  ]
  # يمكنك أيضاً تحديد وقت انتهاء صلاحية الدوال بالثواني (اختياري)
  # timeout = 60 # الافتراضي هو 10 ثوانٍ للدوال المجانية، قد تحتاج لزيادته إذا استغرقت الدالة وقتاً طويلاً

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true