# netlify.toml

[build]
  base = "/"
  publish = "public" # تأكد من وجود هذا السطر وأن المجلد public موجود
  functions = "netlify/functions"

[functions]
  external_node_modules = ["node-fetch"]
  included_files = [
    "node_modules/node-fetch/**",
    "node_modules/mongodb/**",
    "node_modules/bson/**",
    "netlify/functions/arial.ttf"
  ]

# قواعد إعادة التوجيه
[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true