[build]
  base = "/"
  publish = "public"
  functions = "netlify/functions"

[functions]
  included_files = ["public/**"]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true