[build]
  base = "/"
  functions = "netlify/functions"

[functions.generateCertificateTwo2]
  included_files = ["fonts/arial.ttf"]

[[rewrites]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2?id=:id"
  status = 200