[build]
  base = "/"
  functions = "netlify/functions"

[functions.generateCertificateTwo2]
  included_files = ["fonts/arial.ttf"]

[[redirects]]
  from = "/certificate/student/:id"
  to = "/.netlify/functions/generateCertificateTwo2?id=:id"
  status = 200

[[redirects]]
  from = "/images/full/:file"
  to = "/.netlify/images?url=/public/images_temp/:file"
  status = 200