[build]
  base = "/"
  functions = "netlify/functions"

[functions]
  included_files = ["public/**", "netlify/functions/fonts/**", "node_modules/sharp/**"]

[[redirects]]
  from = "/certificate/:id"
  to = "/.netlify/functions/generateCertificateTwo2/:id"
  status = 200
  force = true