[functions]
  directory = "netlify/functions"

[[plugins]]
package = "@netlify/plugin-functions-core"

  [plugins.inputs]
  functions_path = "netlify/functions"
  included_files = ["fonts/arial.ttf", "public/images/الشهادة2.jpg", "fonts/Amiri-Regular.ttf"]