[build]
  base = "/"
  functions = "netlify/functions/teachers" # يشير إلى المجلد الفرعي لوظائف المعلمين

[functions.generateCertificateTwoTeacher4] # أو اسم وظيفتك
  included_files = ["fonts/arial.ttf"]

[[redirects]]
  from = "/teachers/certificate/:id" # أو المسار الذي اخترته
  to = "/.netlify/functions/generateCertificateTwoTeacher4/:id"
  status = 200
  force = true